version = 3
final_space = true
[palette]
  rosewater = "#F4DBD6"
  flamingo = "#F0C6C6"
  blue = "#8AADF4"
  red = "#ED8796"
  green = "#A6DA95"
  mauve = "#C6A0F6"
  yellow = "#EED49F"
  sky = "#91D7E3"
  sapphire = "#7DC4E4"
  lavender = "#B7BDF8"
  text = "#CAD3F5"
  base = "#24273A"
  pink = "#F5BDE6"
  maroon = "#EE99A0"
  peach = "#F5A97F"
  teal = "#8bd5ca"
  overlay0 = "#6E738D"
  surface0 = "#363A4F"
  mantle = "#1e2030"
  crust = "#181926"

[upgrade]
  source = "cdn"
  interval = "168h"
  auto = false
  notice = false

[[blocks]]
  type = "prompt"
  alignment = "left"
  
  [[blocks.segments]]
    type = "text"
    foreground = "p:blue"
    style = "plain"
    template = "\n"

  [[blocks.segments]]
    type = "text"
    foreground = "p:mantle"
    background = "p:blue"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    template = "{{.Shell}}"

  [[blocks.segments]]
    type = "session"
    foreground = "p:base"
    background = "p:rosewater"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    template = "{{if .SSHSession}} {{end}}{{.UserName}}@{{.HostName}}"
    
  [[blocks.segments]]
    template = "{{ .HEAD }}"
    type = "git"
    background = "p:yellow"
    foreground = "p:mantle"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""

    [blocks.segments.properties]
      
      [blocks.segments.properties.mapped_branches]
        "feature/*" = "󱓞 "
    
  [[blocks.segments]]
    type = "python"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "p:mantle"
    background = "p:teal"
    template = " venv"

[[blocks]]
  type="prompt"
  alignment="right"

  [[blocks.segments]]
    template = "{{if .Code}}x{{.Code}}{{end}}"
    foreground = "p:red"
    type = "status"
    style = "plain"  

  [[blocks.segments]]
    type = "executiontime"
    alias = "Ext"
    template = " ext {{.FormattedMs}}"
    foreground = "p:sky"
    style = "plain"

    [blocks.segments.properties]
      threshold = 500
      style="dallas"
          
[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    template = "└[{{ .Path }}]"
    foreground = "p:blue"
    type = "path"
    style="plain"

    [blocks.segments.properties]
      style = "agnoster_full"
      folder_separator_icon = "/"
      home_icon = " home"
      hide_root_location=true
      # max_depth=2
    
    [blocks.segments.properties.mapped_locations]
      # Windows
      "C:\\*" = "C"
      "D:\\*" = "D"
      "D:\\Work\\02_Projects\\01_Business" = " Business"
      "D:\\Work\\02_Projects\\02_Playground" = " Playground"
      "D:\\Work\\02_Projects\\03_DEM" = " DEM"
      "D:\\Work\\02_Projects\\04_College" = " College"

      # Linux
      "/mnt/c/" = "C"
      "/mnt/d/" = "D"
      "~/Projects/01_Business" = " Business"
      "~/Projects/02_Playground" = " Playground"
      "~/Projects/03_DEM" = " DEM"
      "~/Projects/04_College" = " College"
  
[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    template = " "
    foreground = "p:sky"
    type = "text"
    style = "plain"
