version = 3
final_space = true

[[blocks]]
  type = "prompt"
  alignment = "left"
  
  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "cyan"
    template = "\n({{.Shell}})"

  [[blocks.segments]]
    type = "session"
    foreground = "yellow"
    style = "plain"
    template = "{{.UserName}}@{{.HostName}}"
    
  [[blocks.segments]]
    template = "::({{ .HEAD }})"
    type = "git"
    foreground = "yellow"
    style = "plain"

    [blocks.segments.properties]
      branch_icon = ""   

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "green"
    template = "(venv)"

  [[blocks.segments]]
    template = " {{if .Code}}x{{.Code}}{{end}}"
    foreground = "red"
    type = "status"
    style = "plain"  

  [[blocks.segments]]
    type = "executiontime"
    alias = "Ext"
    template = " ext-{{.FormattedMs}}"
    foreground = "white"
    style = "plain"

    [blocks.segments.properties]
      threshold = 500
      style="dallas"
          
[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    template = "~[{{ .Path }}]"
    foreground = "cyan"
    type = "path"
    style="plain"

    [blocks.segments.properties]
      style = "agnoster_full"
      folder_separator_icon = "/"
      home_icon = "home"
      hide_root_location=true
 
[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    template = "$"
    foreground = "cyan"
    type = "text"
    style = "plain"

